name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: generate
        with:
          github_user_name: clarete-ana
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          config_file: config.yml

      - name: Remove progress bar from SVG
        run: |
          sed -i '/<rect id="progress"/d' dist/github-contribution-grid-snake.svg
          sed -i '/<\/rect>/d' dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
